### ISSUE TITLE
Project 1 Idea

### ISSUE THREAD

**Issue by rcliao** [csula/cs4660-fall-2017#2]
Hi all,

This issue is intended to discuss about project. To start with, I'll list some projects I have in mind for us to play.

You can vote each project by either giving it a 👍  if you like it and 👎  if you don't like it.

Around 5th week (September 23), we'll finalize the project and announce the project selection separately.

> If you have any project you have in mind, please comment after the project followed the format an URL to the project and a brief summary on what techniques we will be using in class.

```
Project URL: https://www.example.com/game

Brief description:
Lorem

Potential techniques:
Path finding, minimax, ... etc.
```

**Comment by rcliao** [comment]
https://www.codingame.com/multiplayer/bot-programming/tron-battle

Classic Tron battle game.

**Comment by rcliao** [comment]
http://vindinium.org/

Vindinium, 4 players resource control game.

**Comment by rcliao** [comment]
https://www.codingame.com/multiplayer/bot-programming/coders-of-the-caribbean

Coders of caribbean!

**Comment by rcliao** [comment]
https://sscaitournament.com/

Starcraft Bloodwar competition

**Comment by rcliao** [comment]
https://www.codingame.com/multiplayer/bot-programming/hypersonic

Bomberman

**Comment by rcliao** [comment]
https://screeps.com/forum/topic/1893/tournament-botarena-pure-ai-battle-royale

**Comment by chelleccarlyle** [comment]
Quick Draw!

https://github.com/googlecreativelab/quickdraw-dataset
https://quickdraw.withgoogle.com/data

Demo:
https://quickdraw.withgoogle.com/

**Comment by cowboyuniverse** [comment]
i found a python library for screeps but unsure if it'll work 
https://github.com/screepers/python-screeps

https://screeps.com/

**Comment by rcliao** [comment]
Another option we can run in addition to the Bomberman from CodingGame

https://github.com/EntelectChallenge/2016-Bomberman

**Comment by rcliao** [comment]
Looks like the Tron game and HyperSonic are really close (tie even).

We will be going over with Tron game as the project this semester.
